### ISSUE TITLE
Can't make migrations after config on django1.9 python3.4

### ISSUE THREAD

**Issue by sa-tony** [omab/python-social-auth#801] opened 2015-12-10 21:35 UTC
This is the output info

``` Python
python manage.py makemigrations
/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/django/db/models/fields/subclassing.py:22: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  RemovedInDjango110Warning)
```

**Comment by hellvix** [comment] 2015-12-16 23:33
Hummmm. So this problem comes from Social Auth. Good to know.

**Comment by tkajtoch** [comment] 2015-12-17 10:02
This is just a django warning message. The migrations will be applied.

**Comment by tonyrft** [comment] 2015-12-17 12:43
Yea.... Sorry for my wrong information, but please fix these warnings

**Comment by blueyed** [comment] 2016-01-25 21:01
Dupe of / fixed by #813.

**Comment by omab** [comment] 2016-12-27 15:01
Warnings already fixed.

**Closed by omab** 2016-12-27 15:01 UTC
