### ISSUE TITLE
No named URL resolution in Django

### ISSUE THREAD

**Issue by cassidylaidlaw** [omab/python-social-auth#831] opened 2016-01-30 20:45 UTC
The included Django `auth` app allows for using named URLs in the settings, like so:

```
LOGIN_REDIRECT_URL = 'my_url'
```

However, trying to do the same in `python-social-auth` produces an error because the named URL isn't resolved when the Django strategy retrieves it from the settings.

**Comment by webjunkie** [comment] 2016-03-15 09:45
+1

**Comment by webjunkie** [comment] 2016-04-15 08:35
I had the same problem, but now I don't... and the redirect does seem to use Django's shortcut that also resolves URLs: 0220ae249f0243ab056ef927c964d80de278243e

Can you point to where it does not resolve for you?

**Comment by webjunkie** [comment] 2016-04-20 08:23
Today I ran into the issue again. The problem is when PSA pulls the non-resolved URLs from the settings, they don't appear as valid URLs and are thus not taken into account when redirecting e.g. a new user. I'm going to do a pull request.

**Comment by omab** [comment] 2016-12-13 04:22
With the usage of `resolve_url` this should be fixed (https://github.com/python-social-auth/social-app-django/blob/master/social_django/strategy.py#L49).

**Closed by omab** 2016-12-13 04:22 UTC
