### ISSUE TITLE
Django 1.9 depreciation issue 

### ISSUE THREAD

**Issue by Eclogesh** [omab/python-social-auth#812] opened 2015-12-29 06:53 UTC
C:\w>manage.py makemigrations
C:\Python27\lib\site-packages\django\db\models\fields\subclassing.py:22: Removed
InDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value in
stead.
  RemovedInDjango110Warning)

No changes detected

pip freeze environment is Python 2.7.9 and django 1.9

**Comment by liminspace** [comment] 2016-01-05 14:57
+1

**Comment by blueyed** [comment] 2016-01-25 21:00
Duplicate of / fixed by #813.

**Comment by omab** [comment] 2016-12-13 04:23
Fix already merged.

**Closed by omab** 2016-12-13 04:23 UTC
