### ISSUE TITLE
Django adds migration

### ISSUE THREAD

**Issue by miki725** [omab/python-social-auth#474] opened 2015-01-04 04:37 UTC
When running `$ manage.py makemigrations`, it seems to generate additional migration for `default` app with content:

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocialauth',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='social_auth'),
            preserve_default=True,
        ),
    ]

```

The cause is probably the addition of `related_name` to a [`user` field](https://github.com/omab/python-social-auth/blob/master/social/apps/django_app/default/models.py#L31) which is not represented in the initial [migration](https://github.com/omab/python-social-auth/blob/master/social/apps/django_app/default/migrations/0001_initial.py#L82-L83).

When I manually adjusted the initial migration to include the related_name field, django seemed to treat it just fine.

**Comment by mtirsel** [comment] 2015-01-05 10:07
Duplicate of https://github.com/omab/python-social-auth/issues/426

**Comment by eduardomb** [comment] 2015-02-03 19:56
+1

**Closed** 2015-04-08 07:22 UTC
